// Mock data for development before backend is ready

export const mockBooks = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9780743273565',
    genre: 'Classic',
    description: 'A novel set in the Jazz Age that tells the story of the mysterious millionaire Jay Gatsby and his obsession with the beautiful Daisy Buchanan.',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    averageRating: 4.5,
    reviewCount: 234,
    publicationYear: 1925,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '9780061120084',
    genre: 'Classic',
    description: 'A gripping tale of racial injustice and childhood innocence in the American South during the 1930s.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    averageRating: 4.8,
    reviewCount: 456,
    publicationYear: 1960,
    createdAt: '2024-01-14',
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    isbn: '9780451524935',
    genre: 'Science Fiction',
    description: 'A dystopian social science fiction novel that follows the life of Winston Smith, a low-ranking member of the Party.',
    coverImage: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&h=600&fit=crop',
    averageRating: 4.6,
    reviewCount: 678,
    publicationYear: 1949,
    createdAt: '2024-01-13',
  },
  {
    id: '4',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '9780141439518',
    genre: 'Romance',
    description: 'A romantic novel of manners that follows the character development of Elizabeth Bennet.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    averageRating: 4.7,
    reviewCount: 543,
    publicationYear: 1813,
    createdAt: '2024-01-12',
  },
  {
    id: '5',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    isbn: '9780547928227',
    genre: 'Fantasy',
    description: 'A fantasy novel about the quest of home-loving Bilbo Baggins to win a share of the treasure guarded by Smaug the dragon.',
    coverImage: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&h=600&fit=crop',
    averageRating: 4.9,
    reviewCount: 789,
    publicationYear: 1937,
    createdAt: '2024-01-11',
  },
  {
    id: '6',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    isbn: '9780316769174',
    genre: 'Classic',
    description: 'A story about teenage rebellion and alienation narrated by the cynical Holden Caulfield.',
    coverImage: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop',
    averageRating: 4.2,
    reviewCount: 321,
    publicationYear: 1951,
    createdAt: '2024-01-10',
  },
];

export const mockReviews = [
  {
    id: '1',
    bookId: '1',
    userId: '1',
    userName: 'John Doe',
    userAvatar: 'https://i.pravatar.cc/150?u=john',
    rating: 5,
    text: 'An absolute masterpiece! Fitzgerald\'s prose is beautiful and the story is timeless. The symbolism throughout the novel is incredible.',
    spoiler: false,
    likes: 45,
    isLiked: false,
    createdAt: '2024-02-01',
    comments: [],
  },
  {
    id: '2',
    bookId: '1',
    userId: '2',
    userName: 'Jane Smith',
    userAvatar: 'https://i.pravatar.cc/150?u=jane',
    rating: 4,
    text: 'Great read, though I found some parts a bit slow. The ending was powerful and thought-provoking.',
    spoiler: false,
    likes: 23,
    isLiked: false,
    createdAt: '2024-02-02',
    comments: [],
  },
  {
    id: '3',
    bookId: '2',
    userId: '3',
    userName: 'Bob Johnson',
    userAvatar: 'https://i.pravatar.cc/150?u=bob',
    rating: 5,
    text: 'A must-read for everyone. The themes of justice, morality, and prejudice are as relevant today as they were when the book was written.',
    spoiler: false,
    likes: 67,
    isLiked: true,
    createdAt: '2024-02-03',
    comments: [],
  },
];

export const mockUser = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  bio: 'Book lover and avid reader. I enjoy classic literature and contemporary fiction.',
  avatar: 'https://i.pravatar.cc/150?u=john',
  role: 'user',
  joinDate: '2024-01-01',
  reviewCount: 12,
  followersCount: 45,
  followingCount: 32,
  averageRating: 4.3,
};

export const mockCurrentUser = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'user',
  token: 'mock-jwt-token',
};

export const genres = [
  'All',
  'Classic',
  'Science Fiction',
  'Fantasy',
  'Mystery',
  'Thriller',
  'Romance',
  'Horror',
  'Biography',
  'History',
  'Self-Help',
  'Non-Fiction',
];
